!> Read and Write Files for Insolation.
module data
  use kind, only : dp
  implicit none
  private

  public :: readdata
  public :: writedata

contains

!> Read input from out.dat, generated by snvec
subroutine readdata(time, ecc, obl, prec, lpx, climprec)
  real(dp), intent(out), allocatable :: time(:), ecc(:), obl(:), prec(:), lpx(:), climprec(:)
  integer :: io, ios, i, n
  open(io,file='out.dat', status = "old", action = "read")
  ! first find the number of lines in the file
  n = 0
  do
     read(io,*,iostat=ios)
     if (ios/=0) then
        rewind(io)
        exit
     else
        n=n+1
     end if
  end do
!!$  print *, 'n = ',n ! n is correct
!!$  n = 249481
  allocate(time(n),ecc(n),obl(n),prec(n),lpx(n),climprec(n))
  do i=1,n
  read(io,*) time(i), ecc(i), obl(i), prec(i), lpx(i), climprec(i)
  enddo
  close(io)
end subroutine readdata

!> Write output to ins.dat.
subroutine writedata(time, ecc, obl, prec, lpx, climprec, ins)
  real(dp), intent(in), dimension(:) :: time, ecc, obl, prec, lpx, climprec, ins
  integer :: io,i,n
  n = size(time)
  open (unit=io, file='ins.dat', status="replace", action="write")
  do i=1,n
     write(io,*) time(i), ecc(i), obl(i), prec(i), lpx(i), climprec(i), ins(i)
  enddo
  close(io)
end subroutine writedata

end module data
