#+title: ~paleoinsolation~: New Insolation Forcing for Paleoclimate Models
#+author: Ilja J. Kocken and Richard E. Zeebe
#+date: 2026-01-26

[[https://doi.org/10.5281/zenodo.17478418][https://zenodo.org/badge/DOI/10.5281/zenodo.17478418.svg]]

To facilitate using recent astronomical solutions in [[https://en.wikipedia.org/wiki/General_circulation_model][GCMs]] such as the [[https://www.cesm.ucar.edu/][CESM]], we make the =ZB18a(1,1)= and =ZB20a(1,1)= astronomical solutions readily available.

This code is the supplement to:

Kocken, I.J.  and Zeebe, R.E. (2026). New Insolation Forcing for Paleoclimate Studies.  /Paleoceanography and Paleoclimatology/ *41*, 1. doi: [[https://doi.org/10.1029/2025PA005287][10.1029/2025PA005287]]

* Implementation in PaleoCalAdjust
We aim to make implementation in the Community Earth System Model as easy as possible.

We replace the =GISS_orbpar_subs.f90= file from [[https://github.com/pjbartlein/PaleoCalAdjust/blob/master/f90/modules/GISS_orbpar_subs.f90][GISS_orbpar_subs.f90]] and add necessary data files to the same folder(s). 

1. Download the =GISS_orbpar_subs.f90= file
      #+begin_src sh
        wget https://github.com/japhir/paleoinsolation/raw/refs/heads/main/GISS_orbpar_subs.f90
      #+end_src
2. Choose whether you want to use =ZB18a(1,1)= (default) or =ZB20a(1,1)=
3. Download the appropriate =.bin= file(s) for your desired orbital solution from our [[file:dat/]] directory.
4. Update the path to the data file in the =GISS_orbpar_subs.f90= file.
    Update the filepath in the line that starts with =call readbindata= to the absolute directory of the astronomical solution datafile.
5. Test if it will build.

See [[https://github.com/japhir/paleoinsolation?tab=readme-ov-file#contributing-and-troubleshooting][Contributing and Troubleshooting]] if you need help.
