#+title: ~paleoinsolation~: New Insolation Forcing for Paleoclimate Models

To facilitate using recent astronomical solutions in [[https://en.wikipedia.org/wiki/General_circulation_model][GCMs]] such as the [[https://www.cesm.ucar.edu/][CESM]], we make the ZB18a and ZB20a orbital solutions readily available:

* Overview

We provide a [[file:Makefile]] that downloads the orbital solutions and the [[https://github.com/rezeebe/snvec][snvec C program]], patches snvec to also output the longitude of perihelion, and then compiles and runs snvec for 100 Myr to create the ~ZB18a(1,1)~ and ~ZB20a(1,1)~ solutions (where the numbers in parameters refer to the dynamical ellipticity and the tidal dissipation, respectively).

We provide Fortran subroutines that calculate insolation and interpolate the astronomical parameters to a certain calendar date, and provide drop-in replacements to existing Fortran subroutines from the CESM.

[[https://github.com/CESM-Development/paleoToolkit/tree/master/PaleoCalAdjust][PaleoCalAdjust]]: drop-in replacement for [[https://github.com/CESM-Development/paleoToolkit/blob/master/PaleoCalAdjust/f90/modules/GISS_orbpar_subs.f90][subroutine ~GISS_orbpar~]]

[[https://github.com/ESCOMP/CDEPS/tree/main][CDEPS]]: drop-in replacement for the ~shr_orb_params~ subroutine in the [[https://github.com/ESCOMP/CDEPS/blob/main/share/shr_orb_mod.F90][~shr_orb_mod~]] module.

* Getting Started
#+begin_src sh
  cd ~/ # or wherever you want to install it
  # copy the project over
  git clone 'https://github.com/japhir/paleoinsolation'
  # enter the new directory
  cd 'paleoinsolation'
  # build and run the fortran program
  make
#+end_src

* Contributing
Contributions are welcomed via pull-requests and/or issues.


* References

Zeebe, R. E., & Lourens, L. J. (2019). Solar System chaos and the Paleocene–Eocene boundary age constrained by geology and astronomy. Science, 365 (6456), 926–929. doi: [[https://doi.org/10.1126/science.aax0612][10.1126/science.aax0612]]

Zeebe, R. E., & Lourens, L. J. (2022a). A deep-time dating tool for paleo-applications utilizing obliquity and precession cycles: The role of dynamical ellipticity and tidal dissipation. Paleoceanography and Paleoclimatology, 37 (2), e2021PA004349. doi: [[https://doi.org/10.1029/2021PA004349][10.1029/2021PA004349]]

Zeebe, R. E., & Lourens, L. J. (2022b). Geologically constrained astronomical solutions for the Cenozoic era. Earth and Planetary Science Letters, 592,
375117595. doi: [[https://doi.org/10.1016/j.epsl.2022.117595][10.1016/j.epsl.2022.117595]]
