!> Read and Write Files for Insolation.
module data
  use kind, only : dp
  implicit none
  private

  public :: readdata
  public :: writedata

contains

!> Read input from out.dat, generated by snvec
subroutine readdata(pt_solution_file, time, ecc, obl, prec, lpx, climprec)
  real(dp), intent(out), allocatable :: time(:), ecc(:), obl(:), prec(:), lpx(:), climprec(:)
  integer :: io, ios, i, n
  character(len=*), intent(in) :: pt_solution_file
  character(len=512) :: msg
  open(io,file=pt_solution_file, status = "old", action = "read", &
       iostat=ios, iomsg = msg)
  ! check if file exists/contains anything
  if (ios /= 0) then
     print *, trim(msg)
  else
  ! find the number of lines in the file
     n = 0
     do
        read(io,*,iostat=ios)
        if (ios/=0) then
           rewind(io)
           exit
        else
           n=n+1
        end if
     end do
     allocate(time(n),ecc(n),obl(n),prec(n),lpx(n),climprec(n))
     do i=1,n
        read(io,*) time(i), ecc(i), obl(i), prec(i), lpx(i), climprec(i)
     enddo
  end if
  close(io)
end subroutine readdata

!> Write output to ins_file
subroutine writedata(ins_file, time, ecc, obl, prec, lpx, climprec, ins)
  real(dp), intent(in), dimension(:) :: time, ecc, obl, prec, lpx, climprec, ins
  integer :: io,i,n
  character(len=*) :: ins_file
  n = size(time)
  open (unit=io, file=ins_file, status="replace", action="write")
  do i=1,n
     write(io,*) time(i), ecc(i), obl(i), prec(i), lpx(i), climprec(i), ins(i)
  enddo
  close(io)
end subroutine writedata

end module data
