! 2026-01-26
! Prof. Patrick J. Bartlein pointed me to the latest version
! of the PaleoCalAdjust program, available on 
! https://github.com/pjbartlein/PaleoCalAdjust
! and archived on https://doi.org/10.5281/zenodo.5535025

! Below is the adapted version of our orbpar subroutine
! so that the parameters are the same as v1.1 of the
! GISS_orbpar subroutine. This means this file can be
! used as a drop-in replacement for the original
! GISS_orbpar_subs.f90 file,
! available on:
! https://github.com/pjbartlein/PaleoCalAdjust/blob/master/f90/modules/GISS_orbpar_subs.f90
! and archived on https://doi.org/10.5281/zenodo.5535025

module giss_orbpar_subs

! This moodule is .f90 version of the ORBPAR() subroutine contained in the file
! https://data.giss.nasa.gov/ar5/SOLAR/ORBPAR.FOR downloaded 2017-09-04 17:17
! also retrievable from https://web.archive.org/web/20150920211936/http://data.giss.nasa.gov/ar5/solar.html
    
contains
    
subroutine GISS_orbpars(year_type, year, eccen, obliq_deg, perih_deg, precc)

    implicit none
    
    ! past ages are negative, e.g. 21 ka = 21,000 cal yr BP = -21000, and 1950 CE = 0 cal yr BP = 0 here
    ! NOTE:  Year CE/AD = 0 is assumed to exist, and is equivalent to 1950 BP (-1950)
    
    character(2), intent(in)    :: year_type    ! year type (AD/BC, CE/BCE, BP (1950 CE))
    real(8), intent(in)         :: year        ! Year (negative, e.g. 1900 CE = -50 BP)
    real(8), intent(out)        :: eccen        ! eccentricity of orbital ellipse 
    real(8), intent(out)        :: obliq_deg    ! obliquity (degrees)
    real(8), intent(out)        :: perih_deg    ! longitude of perihelion (degrees)
    real(8), intent(out)        :: precc        ! climatological precession parameter = eccen * sin(omegvp)
 
    real(8)                     :: obliq        ! obliquity (latitude of Tropic of Cancer) (radians)
    real(8)                     :: omegvp       ! longitude of perihelion = spatial angle from vernal equinox to perihelion (radians)

    real(8)                     :: YearCE       ! YearCE -- for consistency with old code (input to ORBPAR() is YearCE)
    real(8)                     :: YearBP       ! YearBP
    real(8)                     :: pi           ! pi
    
    pi=4.0d0*datan(1.0d0)

    ! NOTE:  Year CE/AD = 0 is assumed to exist, and is equivalent to 1950 BP (-1950)
    ! subroutine orbpar() expects real-valued YearCE, but converts to YearBP for calculations
    select case (year_type)
    case ('CE', 'AD', 'ce', 'ad')
        YearCE = year
        YearBP = year - 1950.0d0
    case ('BP', 'bp')
        YearCE = year + 1950.0d0
        YearBP = year
    case default
        stop 'year_type'
    end select
    
    call ORBPAR(yearCE, eccen, obliq, omegvp)
    
    obliq_deg=obliq/((2.0d0*pi)/360.0d0)
    precc=eccen*dsin(omegvp)
    perih_deg=omegvp/((2.0d0*pi)/360.0d0)

end subroutine GISS_orbpars
    
  !===============================================================================
  ! Kocken, I.J. and Zeebe, R.E. (2026). New Insolation Forcing for
  ! Paleoclimate Studies. Paleoceanography and Paleoclimatology 41, 1.
  ! doi: 10.1029/2025PA005287
  !===============================================================================
  !> Read input from out.dat, generated by snvec
  subroutine readdata(pt_solution_file, time, ecc, obl, prec, lpx, climprec)
    real(SHR_KIND_R8), intent(out), allocatable :: time(:), ecc(:), obl(:), prec(:), lpx(:), climprec(:)
    integer(SHR_KIND_IN) :: io, ios, i, n
    character(len=*), intent(in) :: pt_solution_file
    character(len=512) :: msg
    open(io,file=pt_solution_file, status = "old", action = "read", &
         iostat=ios, iomsg = msg)
    ! check if file exists/contains anything
    if (ios /= 0) then
       print *, trim(msg)
    else
       ! find the number of lines in the file
       n = 0
       do
          read(io,*,iostat=ios)
          if (ios/=0) then
             rewind(io)
             exit
          else
             n=n+1
          end if
       end do
       allocate(time(n),ecc(n),obl(n),prec(n),lpx(n),climprec(n))
       do i=1,n
          read(io,*) time(i), ecc(i), obl(i), prec(i), lpx(i), climprec(i)
       enddo
    end if
    close(io)
  end subroutine readdata

  !===============================================================================

  subroutine readbindata(pt_solution_file, time, ecc, obl, prec, lpx, climprec)
    real(SHR_KIND_R8), intent(out), allocatable :: time(:), ecc(:), obl(:), prec(:), lpx(:), climprec(:)
    character(len=*), intent(in) :: pt_solution_file
    ! note that this must be the below Int32 type!
    integer(SHR_KIND_I4) :: n

    ! Read kount as 4-byte integer
    ! Open the binary file in stream mode
    open(unit=10, file=pt_solution_file, access='stream', form='unformatted', status='old', action='read')
    read(10) n
    allocate(time(n), ecc(n), obl(n), prec(n), lpx(n), climprec(n))
    ! Read each array
    read(10) time
    read(10) ecc
    read(10) obl
    read(10) prec
    read(10) lpx
    read(10) climprec
    close(10)

    ! Convert time from days to kyr
    time = time / 365250.0_SHR_KIND_R8
  end subroutine readbindata

  !===============================================================================

  !> Write output to ins_file
  subroutine writedata(ins_file, time, ecc, obl, prec, lpx, climprec, ins)
    real(SHR_KIND_R8), intent(in), dimension(:) :: time, ecc, obl, prec, lpx, climprec, ins
    integer(SHR_KIND_IN) :: i,n
    character(len=*) :: ins_file
    n = size(time)
    open (unit=42, file=ins_file, status="replace", action="write")
    do i=1,n
       write(42,*) time(i), ecc(i), obl(i), prec(i), lpx(i), climprec(i), ins(i)
    enddo
    close(42)
  end subroutine writedata

  !===============================================================================

  ! Below interpolation function adapted from
  ! https://github.com/astrofrog/fortranlib/blob/master/src/lib_array.f90
  ! repeat of their copyright notice follows:
  !
  ! MD5 of template: 13982be359376d65d4f966553ef27636
  ! Array related routines (Integration, Interpolation, etc.)
  !
  ! ------------------------------------------------------------------------------
  ! Copyright (c) 2009-13, Thomas P. Robitaille
  !
  ! All rights reserved.
  !
  ! Redistribution and use in source and binary forms, with or without
  ! modification, are permitted provided that the following conditions are met:
  !
  !  * Redistributions of source code must retain the above copyright notice, this
  !    list of conditions and the following disclaimer.
  !
  !  * Redistributions in binary form must reproduce the above copyright notice,
  !    this list of conditions and the following disclaimer in the documentation
  !    and/or other materials provided with the distribution.
  !
  ! THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  ! AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  ! IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
  ! DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
  ! FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  ! DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  ! SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  ! CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  ! OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  ! OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
  ! ------------------------------------------------------------------------------
  ! locate_dp
  integer function locate(xx,x)
    ! Locate a value in a sorted array
    real(SHR_KIND_R8), dimension(:), intent(in) :: xx
    real(SHR_KIND_R8), intent(in) :: x
    integer(SHR_KIND_IN) :: n,jl,jm,ju
    logical :: ascnd
    n=size(xx)
    ascnd = (xx(n) >= xx(1))
    jl=0
    ju=n+1
    do
       if (ju-jl <= 1) exit
       jm=(ju+jl)/2
       if (ascnd .eqv. (x >= xx(jm))) then
          jl=jm
       else
          ju=jm
       end if
    end do

    if (x == xx(1)) then
       locate = 1
    else if (x == xx(n)) then
       locate = n-1
    else if(ascnd.and. (x > xx(n) .or. x < xx(1))) then
       locate = -1
    else if(.not.ascnd.and. (x < xx(n) .or. x > xx(1))) then
       locate = -1
    else
       locate = jl
    end if
  end function locate

subroutine orbpar(yearCE,ecc,obl,lpx)
  real(dp), intent(in) :: yearCE
  real(dp), intent(out) :: ecc, obl, lpx

  real(dp), save, dimension(:), allocatable :: times, eccs, obls, precs, lpxs, climprecs
  logical, save :: initialized = .false.

  real(dp) :: pi
  real(dp) :: time_kyr

  integer :: n, ipos
  real(dp) :: frac

  pi = 4.0_dp*datan(1.0_dp)
  ! this reads the output file generated by snvec
  ! SOME: add a flag to choose ZB18a or ZB20a?
  if (.not. initialized) then
     ! read from plaintext
!!$     call readdata("dat/PT-ZB18a_1-1.dat", times, eccs, obls, precs, lpxs, climprecs)
     ! read from binary
     call readbindata("dat/PT-ZB18a_1-1.bin", times, eccs, obls, precs, lpxs, climprecs)
!!$     call readbindata("dat/PT-ZB20a_1-1.bin", times, eccs, obls, precs, lpxs, climprecs)
     n = size(times)
     initialized = .true.
     print *, 'Read insolation data from file with save flag'
  else
     n = size(times)
  end if

  ! the DE431 ephimerides used for the ZB18a and ZB20a solutions
  ! has t0 = Julian day 2443144.5003725 (Folkner et al., 2014)
  ! this is approximately 1977-01-01 at 00:00:32 (web tool conversion)

  ! However, Richard Zeebe has taken care of this by first converting
  ! everything t0 to J2000.0

  ! this is the model year in kyr for interpolation
  time_kyr = (yearCE - 2000.0_dp)*1.0e-3_dp

  ! print nice errors if time outside orbital solution is specified
  if((time_kyr .lt. -300.0e3_dp) .or. (time_kyr .gt. 0.0_dp)) then
     print *, 'ERROR: Orbital solution is provided between -300 Myr and 0 Myr.'
     print *, 'time_kyr = ',time_kyr
     error stop
  end if

  ! print warning if time is older then well-constrained eccentricity
  if(time_kyr .lt. -58.0e3_dp) then
     print *, 'Caution: For ZB18a, the interval -300 Myr to -58 Myr is unconstrained due to solar system chaos.'
!!$     print *, 'Caution: For ZB20a, the interval -300 Myr to -71 Myr is unconstrained due to solar system chaos.'
  end if

  ! linear interpolation
  ipos = locate(times,time_kyr)
  if(ipos == -1) then
     print *, 'ERROR: Interpolation out of bounds :',time_kyr,times(1),times(n)
     error stop
  end if

  ! linear interpolation
  frac = ( time_kyr - times(ipos) ) / ( times(ipos+1) - times(ipos) )

  ecc = eccs(ipos) + frac * (eccs(ipos+1) - eccs(ipos))
  obl = obls(ipos) + frac * (obls(ipos+1) - obls(ipos))
  ! prec = linear_interpolation(times,precs,time_kyr)
  lpx = lpxs(ipos) + frac * (lpxs(ipos+1) - lpxs(ipos))

  ! re-wrap
  ! important to do this only at the end!
  lpx = modulo(lpx - pi, 2.0_dp*pi)

  ! climprec = linear_interpolation(times,climprec,time_kyr)
end subroutine orbpar

end module giss_orbpar_subs
