! 2026-01-26
! Prof. Patrick J. Bartlein pointed me to the latest version
! of the PaleoCalAdjust program, available on 
! https://github.com/pjbartlein/PaleoCalAdjust
! and archived on https://doi.org/10.5281/zenodo.5535025

! Below is the adapted version of our orbpar subroutine
! so that the parameters are the same as v1.1 of the
! GISS_orbpar subroutine. This means this file can be
! used as a drop-in replacement for the original
! GISS_orbpar_subs.f90 file,
! available on:
! https://github.com/pjbartlein/PaleoCalAdjust/blob/master/f90/modules/GISS_orbpar_subs.f90
! and archived on https://doi.org/10.5281/zenodo.5535025

module giss_orbpar_subs

! This moodule is .f90 version of the ORBPAR() subroutine contained in the file
! https://data.giss.nasa.gov/ar5/SOLAR/ORBPAR.FOR downloaded 2017-09-04 17:17
! also retrievable from https://web.archive.org/web/20150920211936/http://data.giss.nasa.gov/ar5/solar.html
    
contains
    
subroutine GISS_orbpars(year_type, year, eccen, obliq_deg, perih_deg, precc)

    implicit none
    
    ! past ages are negative, e.g. 21 ka = 21,000 cal yr BP = -21000, and 1950 CE = 0 cal yr BP = 0 here
    ! NOTE:  Year CE/AD = 0 is assumed to exist, and is equivalent to 1950 BP (-1950)
    
    character(2), intent(in)    :: year_type    ! year type (AD/BC, CE/BCE, BP (1950 CE))
    real(8), intent(in)         :: year        ! Year (negative, e.g. 1900 CE = -50 BP)
    real(8), intent(out)        :: eccen        ! eccentricity of orbital ellipse 
    real(8), intent(out)        :: obliq_deg    ! obliquity (degrees)
    real(8), intent(out)        :: perih_deg    ! longitude of perihelion (degrees)
    real(8), intent(out)        :: precc        ! climatological precession parameter = eccen * sin(omegvp)
 
    real(8)                     :: obliq        ! obliquity (latitude of Tropic of Cancer) (radians)
    real(8)                     :: omegvp       ! longitude of perihelion = spatial angle from vernal equinox to perihelion (radians)

    real(8)                     :: YearCE       ! YearCE -- for consistency with old code (input to ORBPAR() is YearCE)
    real(8)                     :: YearBP       ! YearBP
    real(8)                     :: pi           ! pi
    
    pi=4.0d0*datan(1.0d0)

    ! NOTE:  Year CE/AD = 0 is assumed to exist, and is equivalent to 1950 BP (-1950)
    ! subroutine orbpar() expects real-valued YearCE, but converts to YearBP for calculations
    select case (year_type)
    case ('CE', 'AD', 'ce', 'ad')
        YearCE = year
        YearBP = year - 1950.0d0
    case ('BP', 'bp')
        YearCE = year + 1950.0d0
        YearBP = year
    case default
        stop 'year_type'
    end select
    
    call ORBPAR(yearCE, eccen, obliq, omegvp)
    
    obliq_deg=obliq/((2.0d0*pi)/360.0d0)
    precc=eccen*dsin(omegvp)
    perih_deg=omegvp/((2.0d0*pi)/360.0d0)

end subroutine GISS_orbpars
    
subroutine orbpar(yearCE,ecc,obl,lpx)
  real(dp), intent(in) :: yearCE
  real(dp), intent(out) :: ecc, obl, lpx

  real(dp), save, dimension(:), allocatable :: times, eccs, obls, precs, lpxs, climprecs
  logical, save :: initialized = .false.

  real(dp) :: pi
  real(dp) :: time_kyr

  integer :: n, ipos
  real(dp) :: frac

  pi = 4.0_dp*datan(1.0_dp)
  ! this reads the output file generated by snvec
  ! SOME: add a flag to choose ZB18a or ZB20a?
  if (.not. initialized) then
     ! read from plaintext
!!$     call readdata("dat/PT-ZB18a_1-1.dat", times, eccs, obls, precs, lpxs, climprecs)
     ! read from binary
     call readbindata("dat/PT-ZB18a_1-1.bin", times, eccs, obls, precs, lpxs, climprecs)
!!$     call readbindata("dat/PT-ZB20a_1-1.bin", times, eccs, obls, precs, lpxs, climprecs)
     n = size(times)
     initialized = .true.
     print *, 'Read insolation data from file with save flag'
  else
     n = size(times)
  end if

  ! the DE431 ephimerides used for the ZB18a and ZB20a solutions
  ! has t0 = Julian day 2443144.5003725 (Folkner et al., 2014)
  ! this is approximately 1977-01-01 at 00:00:32 (web tool conversion)

  ! However, Richard Zeebe has taken care of this by first converting
  ! everything t0 to J2000.0

  ! this is the model year in kyr for interpolation
  time_kyr = (yearCE - 2000.0_dp)*1.0e-3_dp

  ! print nice errors if time outside orbital solution is specified
  if((time_kyr .lt. -300.0e3_dp) .or. (time_kyr .gt. 0.0_dp)) then
     print *, 'ERROR: Orbital solution is provided between -300 Myr and 0 Myr.'
     print *, 'time_kyr = ',time_kyr
     error stop
  end if

  ! print warning if time is older then well-constrained eccentricity
  if(time_kyr .lt. -58.0e3_dp) then
     print *, 'Caution: For ZB18a, the interval -300 Myr to -58 Myr is unconstrained due to solar system chaos.'
!!$     print *, 'Caution: For ZB20a, the interval -300 Myr to -71 Myr is unconstrained due to solar system chaos.'
  end if

  ! linear interpolation
  ipos = locate(times,time_kyr)
  if(ipos == -1) then
     print *, 'ERROR: Interpolation out of bounds :',time_kyr,times(1),times(n)
     error stop
  end if

  ! linear interpolation
  frac = ( time_kyr - times(ipos) ) / ( times(ipos+1) - times(ipos) )

  ecc = eccs(ipos) + frac * (eccs(ipos+1) - eccs(ipos))
  obl = obls(ipos) + frac * (obls(ipos+1) - obls(ipos))
  ! prec = linear_interpolation(times,precs,time_kyr)
  lpx = lpxs(ipos) + frac * (lpxs(ipos+1) - lpxs(ipos))

  ! re-wrap
  ! important to do this only at the end!
  lpx = modulo(lpx - pi, 2.0_dp*pi)

  ! climprec = linear_interpolation(times,climprec,time_kyr)
end subroutine orbpar

end module giss_orbpar_subs
